# Generated by Django 4.1.7 on 2023-02-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('other', 'Разное'), ('food', 'Еда'), ('electronics', 'Электроника'), ('dishes', 'Посуда')], default='other', verbose_name='Категория'),
        ),
    ]
