# Generated by Django 4.1.7 on 2023-02-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(verbose_name='Фото товара'),
        ),
    ]
