# Generated by Django 4.1.7 on 2023-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=10000, verbose_name='Фото товара'),
        ),
    ]
