# Generated by Django 4.1.7 on 2023-03-13 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Остаток')),
                ('product_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='e_shop.product', verbose_name='Товар')),
            ],
        ),
    ]
