# Generated by Django 4.1.7 on 2023-03-14 08:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0006_itemincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.IntegerField(max_length=100, verbose_name='Имя пользователя')),
                ('phone_number', models.IntegerField(max_length=12, verbose_name='Телефон')),
                ('address', models.IntegerField(max_length=12, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания')),
            ],
        ),
        migrations.AlterField(
            model_name='itemincart',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_shop.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='product_pk',
            field=models.ManyToManyField(blank=True, related_name='product_booking', through='e_shop.Count', to='e_shop.product', verbose_name='Товары'),
        ),
    ]
