# Generated by Django 4.1.7 on 2023-03-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0007_booking_alter_itemincart_count_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='count',
            name='product',
        ),
        migrations.AddField(
            model_name='count',
            name='booking_pk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='e_shop.booking', verbose_name='Id заказа'),
        ),
        migrations.AddField(
            model_name='count',
            name='product_pk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='e_shop.product', verbose_name='Id продукта'),
        ),
    ]
