# Generated by Django 4.1.7 on 2023-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0008_remove_count_booking_remove_count_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
