# Generated by Django 4.1.7 on 2023-03-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0009_alter_booking_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=12, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
